-- The schema lives in packages/ask-question/supabase/migrations/ so that the
-- setup CLI can copy it into a consuming project and the Supabase CLI can
-- apply it in order.
--
--   packages/ask-question/supabase/migrations/0001_create_answers.sql
--   packages/ask-question/supabase/migrations/0002_add_session_id.sql
--
-- Apply them with `pnpm exec askq-setup`, or by hand with `supabase db push`.
-- Every migration is written to be safe to run more than once.
